site_name: !ENV [ SITE_NAME, 'Doctrine Diagram Bundle' ]
theme: readthedocs
copyright: © 2024 Jawira Portugal
site_author: Jawira Portugal
strict: true
use_directory_urls: false
nav:
    - 'dev-notes.md'
