name: Bundle install

on:
  pull_request:

jobs:
  sy60:
    strategy:
      matrix:
        sf: [ '6.0.*' ]
        php: [ '8.0', '8.1', '8.2' , '8.3' ]
        composer-flags: [ '--prefer-lower', '--ansi' ]
    uses: jawira/doctrine-diagram-bundle/.github/workflows/install-bundle.yaml@update-ga
    with:
      symfony: ${{ matrix.sf }}
      php: ${{ matrix.php }}
      composer-flags: ${{ matrix.composer-flags }}

  sy61:
    strategy:
      matrix:
        sf: [ '6.1.*','6.2.*','6.3.*','6.4.*' ]
        php: [ '8.1', '8.2' , '8.3' ]
    uses: jawira/doctrine-diagram-bundle/.github/workflows/install-bundle.yaml@update-ga
    with:
      symfony: ${{ matrix.sf }}
      php: ${{ matrix.php }}
      composer-flags: ${{ matrix.composer-flags }}

  sy70:
    strategy:
      matrix:
        sf: [ '7.0.*' ]
        php: [ '8.2' , '8.3' ]
    uses: jawira/doctrine-diagram-bundle/.github/workflows/install-bundle.yaml@update-ga
    with:
      symfony: ${{ matrix.sf }}
      php: ${{ matrix.php }}
      composer-flags: ${{ matrix.composer-flags }}
